### ISSUE TITLE
Keyerror: database_uri

### ISSUE THREAD

**Issue by LucasAlgerDay** [orangethewell/Mona-Bot#2]
![Screenshot_20220126-081203](https://user-images.githubusercontent.com/88118098/151190656-5b23d318-703e-4b9a-9766-fb50e6a21c83.png)

When I tried to run always give me that error, in pc, heroku, pydroid, etc.

**Comment by orangethewell** [comment]
Sorry for the long wait. Basically, the `DATABASE_URI` is a _environment variable_. You need to set this as local variable or change the arg to a database of your choice. On Heroku, you can setup a database and the enviroment will work automatically, on your mobile or any other, you need to create a file (SQLite) or setup a SQL Server. To create a database with SQLite you Just change the argument to "sqlite:///Path/to/your/database.db" and it will work, changing to the Path to your database file.

The server you will need to search on Google how to, I don't know how the server setup works.

**Comment by orangethewell** [comment]
since I had no response, I will close it.
